name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Pull repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake files
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: abirahamlincoln
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      # Deploy to output branch for GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
