name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clean old dist
        run: rm -rf dist

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: abirahamlincoln
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
